-- P0 Security Hotfix
--
-- Menutup tiga celah kritis hasil audit:
--   1. Pengguna terautentikasi dapat mengubah kredit/tier/expiry langsung dari Data API.
--   2. Checkout memberi benefit tanpa pembayaran terverifikasi (tanpa order, idempotensi, atau ledger).
--   3. Pengurangan kredit, penyimpanan ujian, dan ledger tidak atomik (race + partial write).
--
-- Prinsip: semua mutasi kredit hanya melalui fungsi security definer yang mengunci baris profil
-- (SELECT ... FOR UPDATE), menulis ledger, dan idempoten terhadap idempotency key.

-- ---------------------------------------------------------------------------
-- 1. Cabut akses UPDATE langsung ke kolom billing pada profil
-- ---------------------------------------------------------------------------

revoke update on public.profiles from authenticated;
revoke update on public.profiles from anon;
revoke insert, delete on public.profiles from authenticated;
revoke insert, delete on public.profiles from anon;

drop policy if exists "Users can update own profile" on public.profiles;

-- Satu-satunya jalur update profil untuk pengguna: ubah nama saja.
create or replace function public.update_own_profile(p_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
begin
  if p_name is null or length(btrim(p_name)) < 2 then
    raise exception 'Nama minimal 2 karakter.' using errcode = '22023';
  end if;

  if length(btrim(p_name)) > 120 then
    raise exception 'Nama maksimal 120 karakter.' using errcode = '22023';
  end if;

  update public.profiles
     set name = btrim(p_name)
   where auth_user_id = auth.uid()
  returning * into v_profile;

  if v_profile.id is null then
    raise exception 'Profil tidak ditemukan.' using errcode = 'P0002';
  end if;

  return to_jsonb(v_profile);
end;
$$;

revoke all on function public.update_own_profile(text) from public;
revoke all on function public.update_own_profile(text) from anon;
grant execute on function public.update_own_profile(text) to authenticated;

-- Ledger dan order tidak boleh ditulis klien; hanya service role (bypass RLS).
revoke insert, update, delete on public.credit_transactions from authenticated;
revoke insert, update, delete on public.credit_transactions from anon;

-- ---------------------------------------------------------------------------
-- 2. Kolom idempotensi pada ledger dan sesi ujian
-- ---------------------------------------------------------------------------

alter table public.credit_transactions
  add column if not exists idempotency_key text,
  add column if not exists reference_type text,
  add column if not exists reference_id text;

create unique index if not exists credit_transactions_idempotency_key_idx
  on public.credit_transactions (idempotency_key)
  where idempotency_key is not null;

create index if not exists credit_transactions_reference_idx
  on public.credit_transactions (reference_type, reference_id)
  where reference_id is not null;

alter table public.exam_sessions
  add column if not exists idempotency_key text;

create unique index if not exists exam_sessions_idempotency_key_idx
  on public.exam_sessions (idempotency_key)
  where idempotency_key is not null;

-- ---------------------------------------------------------------------------
-- 3. Payment orders (sumber kebenaran pembayaran)
-- ---------------------------------------------------------------------------

create table if not exists public.payment_orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  package_id text not null,
  order_type text not null check (order_type in ('topup', 'subscription')),
  provider text not null default 'mayar',
  provider_order_id text unique,
  provider_transaction_id text,
  status text not null default 'pending' check (status in ('pending', 'paid', 'expired', 'failed', 'cancelled')),
  amount integer not null check (amount >= 0),
  credits integer not null check (credits >= 0),
  duration_months integer,
  checkout_url text,
  customer_name text,
  customer_email text,
  customer_mobile text,
  paid_at timestamptz,
  fulfilled_at timestamptz,
  credits_granted integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists payment_orders_user_created_idx
  on public.payment_orders (user_id, created_at desc);

create index if not exists payment_orders_status_idx
  on public.payment_orders (status);

drop trigger if exists payment_orders_set_updated_at on public.payment_orders;
create trigger payment_orders_set_updated_at
before update on public.payment_orders
for each row execute function public.set_updated_at();

alter table public.payment_orders enable row level security;

revoke insert, update, delete on public.payment_orders from authenticated;
revoke insert, update, delete on public.payment_orders from anon;

-- RLS hanya menyaring baris; akses tabel tetap butuh GRANT eksplisit.
grant select on public.payment_orders to authenticated;
revoke select on public.payment_orders from anon;

drop policy if exists "Users can read own payment orders" on public.payment_orders;
create policy "Users can read own payment orders"
on public.payment_orders for select
to authenticated
using (user_id in (select id from public.profiles where auth_user_id = auth.uid()));

-- ---------------------------------------------------------------------------
-- 4. RPC kredit transaksional
-- ---------------------------------------------------------------------------

-- Mengurangi saldo, menulis ledger, dan mengunci baris profil dalam satu transaksi.
create or replace function public.spend_credits(
  p_profile_id bigint,
  p_amount integer,
  p_idempotency_key text,
  p_description text default null,
  p_reference_type text default null,
  p_reference_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
  v_transaction_id bigint;
  v_balance integer;
begin
  if p_amount is null or p_amount <= 0 then
    raise exception 'Jumlah kredit tidak valid.' using errcode = '22023';
  end if;

  if p_idempotency_key is null or length(p_idempotency_key) < 8 then
    raise exception 'Idempotency key wajib diisi minimal 8 karakter.' using errcode = '22023';
  end if;

  select id into v_transaction_id
  from public.credit_transactions
  where idempotency_key = p_idempotency_key;

  if v_transaction_id is not null then
    select credits_balance into v_balance from public.profiles where id = p_profile_id;
    return jsonb_build_object(
      'applied', false,
      'reason', 'duplicate',
      'credits_balance', coalesce(v_balance, 0),
      'transaction_id', v_transaction_id
    );
  end if;

  select * into v_profile
  from public.profiles
  where id = p_profile_id
  for update;

  if v_profile.id is null then
    raise exception 'Profil pengguna tidak ditemukan.' using errcode = 'P0002';
  end if;

  if v_profile.credits_balance < p_amount then
    raise exception 'insufficient_credits'
      using errcode = 'P0001',
            detail = jsonb_build_object(
              'credits_balance', v_profile.credits_balance,
              'credits_required', p_amount
            )::text;
  end if;

  update public.profiles
     set credits_balance = credits_balance - p_amount
   where id = p_profile_id
  returning credits_balance into v_balance;

  insert into public.credit_transactions (
    user_id, type, amount, description, idempotency_key, reference_type, reference_id
  ) values (
    p_profile_id, 'deduction', -p_amount, p_description, p_idempotency_key, p_reference_type, p_reference_id
  )
  returning id into v_transaction_id;

  return jsonb_build_object(
    'applied', true,
    'credits_balance', v_balance,
    'transaction_id', v_transaction_id
  );
exception
  when unique_violation then
    -- Balapan idempotency: transaksi lain sudah memakai key ini, batalkan efek kita.
    select id into v_transaction_id
    from public.credit_transactions
    where idempotency_key = p_idempotency_key;

    select credits_balance into v_balance from public.profiles where id = p_profile_id;

    return jsonb_build_object(
      'applied', false,
      'reason', 'duplicate',
      'credits_balance', coalesce(v_balance, 0),
      'transaction_id', v_transaction_id
    );
end;
$$;

-- Mengembalikan kredit yang sudah terpotong ketika proses lanjutan gagal.
create or replace function public.refund_credits(
  p_profile_id bigint,
  p_amount integer,
  p_idempotency_key text,
  p_description text default null,
  p_reference_type text default null,
  p_reference_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_transaction_id bigint;
  v_balance integer;
begin
  if p_amount is null or p_amount <= 0 then
    raise exception 'Jumlah kredit tidak valid.' using errcode = '22023';
  end if;

  if p_idempotency_key is null or length(p_idempotency_key) < 8 then
    raise exception 'Idempotency key wajib diisi minimal 8 karakter.' using errcode = '22023';
  end if;

  select id into v_transaction_id
  from public.credit_transactions
  where idempotency_key = p_idempotency_key;

  if v_transaction_id is not null then
    select credits_balance into v_balance from public.profiles where id = p_profile_id;
    return jsonb_build_object(
      'applied', false,
      'reason', 'duplicate',
      'credits_balance', coalesce(v_balance, 0),
      'transaction_id', v_transaction_id
    );
  end if;

  perform 1 from public.profiles where id = p_profile_id for update;

  update public.profiles
     set credits_balance = credits_balance + p_amount
   where id = p_profile_id
  returning credits_balance into v_balance;

  if v_balance is null then
    raise exception 'Profil pengguna tidak ditemukan.' using errcode = 'P0002';
  end if;

  insert into public.credit_transactions (
    user_id, type, amount, description, idempotency_key, reference_type, reference_id
  ) values (
    p_profile_id, 'bonus', p_amount, p_description, p_idempotency_key, p_reference_type, p_reference_id
  )
  returning id into v_transaction_id;

  return jsonb_build_object(
    'applied', true,
    'credits_balance', v_balance,
    'transaction_id', v_transaction_id
  );
exception
  when unique_violation then
    select id into v_transaction_id
    from public.credit_transactions
    where idempotency_key = p_idempotency_key;

    select credits_balance into v_balance from public.profiles where id = p_profile_id;

    return jsonb_build_object(
      'applied', false,
      'reason', 'duplicate',
      'credits_balance', coalesce(v_balance, 0),
      'transaction_id', v_transaction_id
    );
end;
$$;

-- Menyimpan sesi ujian + soal + pemotongan kredit dalam satu transaksi.
create or replace function public.create_exam_with_credits(
  p_profile_id bigint,
  p_exam jsonb,
  p_questions jsonb,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
  v_exam public.exam_sessions;
  v_cost integer;
  v_balance integer;
  v_transaction_id bigint;
  v_questions jsonb;
begin
  if p_idempotency_key is null or length(p_idempotency_key) < 8 then
    raise exception 'Idempotency key wajib diisi minimal 8 karakter.' using errcode = '22023';
  end if;

  if p_questions is null or jsonb_typeof(p_questions) <> 'array' or jsonb_array_length(p_questions) = 0 then
    raise exception 'Daftar soal tidak valid.' using errcode = '22023';
  end if;

  v_cost := jsonb_array_length(p_questions);

  select * into v_exam
  from public.exam_sessions
  where idempotency_key = p_idempotency_key;

  if v_exam.id is not null then
    select credits_balance into v_balance from public.profiles where id = p_profile_id;
    select coalesce(jsonb_agg(to_jsonb(q) order by q.order_number), '[]'::jsonb) into v_questions
    from public.questions q where q.exam_session_id = v_exam.id;

    return jsonb_build_object(
      'applied', false,
      'reason', 'duplicate',
      'exam', to_jsonb(v_exam),
      'questions', v_questions,
      'credits_balance', coalesce(v_balance, 0)
    );
  end if;

  select * into v_profile
  from public.profiles
  where id = p_profile_id
  for update;

  if v_profile.id is null then
    raise exception 'Profil pengguna tidak ditemukan.' using errcode = 'P0002';
  end if;

  if v_profile.credits_balance < v_cost then
    raise exception 'insufficient_credits'
      using errcode = 'P0001',
            detail = jsonb_build_object(
              'credits_balance', v_profile.credits_balance,
              'credits_required', v_cost
            )::text;
  end if;

  insert into public.exam_sessions (
    user_id, curriculum, exam_type, class_phase, subject, semester, time_allocation,
    reference_type, difficulty, cognitive_levels, pg_options, include_illustration, topics,
    credits_consumed, idempotency_key
  ) values (
    p_profile_id,
    p_exam->>'curriculum',
    p_exam->>'exam_type',
    p_exam->>'class_phase',
    p_exam->>'subject',
    coalesce(p_exam->>'semester', 'Ganjil'),
    coalesce((p_exam->>'time_allocation')::integer, 90),
    coalesce(p_exam->>'reference_type', 'AI'),
    coalesce(p_exam->>'difficulty', 'Campuran Berimbang'),
    coalesce(p_exam->'cognitive_levels', '[]'::jsonb),
    p_exam->>'pg_options',
    coalesce((p_exam->>'include_illustration')::boolean, false),
    coalesce(p_exam->'topics', '[]'::jsonb),
    v_cost,
    p_idempotency_key
  )
  returning * into v_exam;

  insert into public.questions (
    exam_session_id, order_number, question_type, cognitive_level, difficulty,
    question_content, options, correct_answer, illustration_prompt, illustration_image
  )
  select
    v_exam.id,
    coalesce(nullif(q->>'order_number', '')::integer, t.ordinality::integer),
    coalesce(q->>'question_type', 'Pilihan Ganda'),
    q->>'cognitive_level',
    q->>'difficulty',
    coalesce(q->>'question_content', ''),
    case
      when q->'options' is null or jsonb_typeof(q->'options') = 'null' then null
      else q->'options'
    end,
    coalesce(q->>'correct_answer', ''),
    q->>'illustration_prompt',
    q->>'illustration_image'
  from jsonb_array_elements(p_questions) with ordinality as t(q, ordinality);

  update public.profiles
     set credits_balance = credits_balance - v_cost
   where id = p_profile_id
  returning credits_balance into v_balance;

  insert into public.credit_transactions (
    user_id, type, amount, description, idempotency_key, reference_type, reference_id
  ) values (
    p_profile_id,
    'deduction',
    -v_cost,
    format('Generate %s soal: %s - %s', v_cost, v_exam.subject, v_exam.exam_type),
    p_idempotency_key,
    'exam_session',
    v_exam.id::text
  )
  returning id into v_transaction_id;

  select coalesce(jsonb_agg(to_jsonb(q) order by q.order_number), '[]'::jsonb) into v_questions
  from public.questions q where q.exam_session_id = v_exam.id;

  return jsonb_build_object(
    'applied', true,
    'exam', to_jsonb(v_exam),
    'questions', v_questions,
    'credits_balance', v_balance,
    'transaction_id', v_transaction_id
  );
exception
  when unique_violation then
    select * into v_exam from public.exam_sessions where idempotency_key = p_idempotency_key;

    if v_exam.id is null then
      raise;
    end if;

    select credits_balance into v_balance from public.profiles where id = p_profile_id;
    select coalesce(jsonb_agg(to_jsonb(q) order by q.order_number), '[]'::jsonb) into v_questions
    from public.questions q where q.exam_session_id = v_exam.id;

    return jsonb_build_object(
      'applied', false,
      'reason', 'duplicate',
      'exam', to_jsonb(v_exam),
      'questions', v_questions,
      'credits_balance', coalesce(v_balance, 0)
    );
end;
$$;

-- Fulfillment order pembayaran: satu-satunya jalur pemberian kredit/premium dari pembayaran.
create or replace function public.fulfill_payment_order(
  p_order_id bigint,
  p_provider_status text,
  p_provider_transaction_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.payment_orders;
  v_profile public.profiles;
  v_expiry timestamptz;
  v_tier public.subscription_tier;
  v_granted integer;
begin
  if p_order_id is null then
    raise exception 'Order tidak valid.' using errcode = '22023';
  end if;

  select * into v_order
  from public.payment_orders
  where id = p_order_id
  for update;

  if v_order.id is null then
    raise exception 'Order pembayaran tidak ditemukan.' using errcode = 'P0002';
  end if;

  if p_provider_transaction_id is not null and v_order.provider_transaction_id is distinct from p_provider_transaction_id then
    update public.payment_orders
       set provider_transaction_id = p_provider_transaction_id
     where id = v_order.id;
    v_order.provider_transaction_id := p_provider_transaction_id;
  end if;

  if coalesce(p_provider_status, '') <> 'paid' then
    if v_order.status = 'pending' and p_provider_status in ('expired', 'failed', 'cancelled') then
      update public.payment_orders
         set status = p_provider_status
       where id = v_order.id;

      v_order.status := p_provider_status;
    end if;

    return jsonb_build_object(
      'applied', false,
      'reason', coalesce(p_provider_status, 'unknown'),
      'order_id', v_order.id,
      'status', v_order.status
    );
  end if;

  if v_order.status = 'paid' then
    select * into v_profile from public.profiles where id = v_order.user_id;

    return jsonb_build_object(
      'applied', false,
      'reason', 'already_paid',
      'order_id', v_order.id,
      'status', 'paid',
      'profile', to_jsonb(v_profile)
    );
  end if;

  select * into v_profile
  from public.profiles
  where id = v_order.user_id
  for update;

  if v_profile.id is null then
    raise exception 'Profil pengguna tidak ditemukan.' using errcode = 'P0002';
  end if;

  v_expiry := v_profile.subscription_expiry;
  v_tier := v_profile.subscription_tier;

  if v_order.order_type = 'subscription' then
    if v_expiry is not null and v_expiry > now() then
      v_expiry := v_expiry + make_interval(months => coalesce(v_order.duration_months, 1));
    else
      v_expiry := now() + make_interval(months => coalesce(v_order.duration_months, 1));
    end if;

    v_tier := 'premium';
  end if;

  v_granted := v_order.credits;

  update public.profiles
     set credits_balance = credits_balance + v_granted,
         subscription_tier = v_tier,
         subscription_expiry = v_expiry
   where id = v_profile.id
  returning * into v_profile;

  insert into public.credit_transactions (
    user_id, type, amount, description, idempotency_key, reference_type, reference_id
  ) values (
    v_profile.id,
    case when v_order.order_type = 'subscription' then 'subscription'::public.credit_transaction_type
         else 'topup'::public.credit_transaction_type end,
    v_granted,
    format('%s - order #%s', v_order.package_id, v_order.id),
    'payment_order:' || v_order.id::text,
    'payment_order',
    v_order.id::text
  )
  on conflict (idempotency_key) where idempotency_key is not null do nothing;

  update public.payment_orders
     set status = 'paid',
         paid_at = coalesce(paid_at, now()),
         fulfilled_at = now(),
         credits_granted = v_granted
   where id = v_order.id;

  return jsonb_build_object(
    'applied', true,
    'reason', 'fulfilled',
    'order_id', v_order.id,
    'status', 'paid',
    'credits_granted', v_granted,
    'profile', to_jsonb(v_profile)
  );
end;
$$;

-- RPC sensitif hanya boleh dipanggil service role (Edge Function).
revoke all on function public.spend_credits(bigint, integer, text, text, text, text) from public;
revoke all on function public.refund_credits(bigint, integer, text, text, text, text) from public;
revoke all on function public.create_exam_with_credits(bigint, jsonb, jsonb, text) from public;
revoke all on function public.fulfill_payment_order(bigint, text, text) from public;

revoke all on function public.spend_credits(bigint, integer, text, text, text, text) from anon, authenticated;
revoke all on function public.refund_credits(bigint, integer, text, text, text, text) from anon, authenticated;
revoke all on function public.create_exam_with_credits(bigint, jsonb, jsonb, text) from anon, authenticated;
revoke all on function public.fulfill_payment_order(bigint, text, text) from anon, authenticated;

grant execute on function public.spend_credits(bigint, integer, text, text, text, text) to service_role;
grant execute on function public.refund_credits(bigint, integer, text, text, text, text) to service_role;
grant execute on function public.create_exam_with_credits(bigint, jsonb, jsonb, text) to service_role;
grant execute on function public.fulfill_payment_order(bigint, text, text) to service_role;
