create extension if not exists pgcrypto;

do $$ begin
  create type public.subscription_tier as enum ('free', 'basic', 'premium');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.credit_transaction_type as enum ('topup', 'subscription', 'deduction', 'bonus');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  subscription_tier public.subscription_tier not null default 'free',
  credits_balance integer not null default 10 check (credits_balance >= 0),
  subscription_expiry timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.credit_transactions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  type public.credit_transaction_type not null,
  amount integer not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.exam_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  curriculum text not null,
  exam_type text not null,
  class_phase text not null,
  subject text not null,
  semester text not null default 'Ganjil',
  time_allocation integer not null default 90,
  reference_type text not null default 'AI',
  difficulty text not null default 'Campuran Berimbang',
  cognitive_levels jsonb,
  pg_options text,
  include_illustration boolean not null default false,
  topics jsonb,
  credits_consumed integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  exam_session_id bigint not null references public.exam_sessions(id) on delete cascade,
  order_number integer not null default 0,
  question_type text not null,
  cognitive_level text,
  difficulty text,
  question_content text not null,
  options jsonb,
  correct_answer text not null,
  illustration_prompt text,
  illustration_image text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_auth_user_id_idx on public.profiles(auth_user_id);
create index if not exists exam_sessions_user_created_idx on public.exam_sessions(user_id, created_at desc);
create index if not exists questions_exam_order_idx on public.questions(exam_session_id, order_number);
create index if not exists credit_transactions_user_created_idx on public.credit_transactions(user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists exam_sessions_set_updated_at on public.exam_sessions;
create trigger exam_sessions_set_updated_at
before update on public.exam_sessions
for each row execute function public.set_updated_at();

drop trigger if exists questions_set_updated_at on public.questions;
create trigger questions_set_updated_at
before update on public.questions
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_profile_id bigint;
begin
  insert into public.profiles (auth_user_id, name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1), 'Pengguna'),
    new.email
  )
  on conflict (auth_user_id) do update
    set name = excluded.name,
        email = excluded.email
  returning id into inserted_profile_id;

  insert into public.credit_transactions (user_id, type, amount, description)
  values (inserted_profile_id, 'bonus', 10, 'Kredit gratis selamat datang untuk pengguna baru.')
  on conflict do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.credit_transactions enable row level security;
alter table public.exam_sessions enable row level security;
alter table public.questions enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select
to authenticated
using (auth_user_id = auth.uid());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update
to authenticated
using (auth_user_id = auth.uid())
with check (auth_user_id = auth.uid());

drop policy if exists "Users can read own transactions" on public.credit_transactions;
create policy "Users can read own transactions"
on public.credit_transactions for select
to authenticated
using (user_id in (select id from public.profiles where auth_user_id = auth.uid()));

drop policy if exists "Users can read own exams" on public.exam_sessions;
create policy "Users can read own exams"
on public.exam_sessions for select
to authenticated
using (user_id in (select id from public.profiles where auth_user_id = auth.uid()));

drop policy if exists "Users can delete own exams" on public.exam_sessions;
create policy "Users can delete own exams"
on public.exam_sessions for delete
to authenticated
using (user_id in (select id from public.profiles where auth_user_id = auth.uid()));

drop policy if exists "Users can read own questions" on public.questions;
create policy "Users can read own questions"
on public.questions for select
to authenticated
using (
  exam_session_id in (
    select exam_sessions.id
    from public.exam_sessions
    join public.profiles on profiles.id = exam_sessions.user_id
    where profiles.auth_user_id = auth.uid()
  )
);

drop policy if exists "Users can update own questions" on public.questions;
create policy "Users can update own questions"
on public.questions for update
to authenticated
using (
  exam_session_id in (
    select exam_sessions.id
    from public.exam_sessions
    join public.profiles on profiles.id = exam_sessions.user_id
    where profiles.auth_user_id = auth.uid()
  )
)
with check (
  exam_session_id in (
    select exam_sessions.id
    from public.exam_sessions
    join public.profiles on profiles.id = exam_sessions.user_id
    where profiles.auth_user_id = auth.uid()
  )
);

insert into storage.buckets (id, name, public)
values ('question-illustrations', 'question-illustrations', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can read question illustrations" on storage.objects;
create policy "Public can read question illustrations"
on storage.objects for select
to public
using (bucket_id = 'question-illustrations');
