-- Bank soal pribadi. Soal disalin sebagai snapshot agar tetap tersedia walau
-- sesi ujian sumber dihapus atau diedit. Fingerprint unik per user mencegah
-- konten identik tersimpan lebih dari sekali.

create table if not exists public.question_bank (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  source_question_id bigint references public.questions(id) on delete set null,
  subject text not null,
  class_phase text not null,
  topic text,
  difficulty text,
  question_type text not null,
  cognitive_level text,
  question_content text not null,
  options jsonb,
  correct_answer text not null,
  explanation text,
  illustration_prompt text,
  illustration_image text,
  content_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, content_hash)
);

create index if not exists question_bank_filter_idx
  on public.question_bank(user_id, subject, class_phase, difficulty, created_at desc);
create index if not exists question_bank_topic_idx
  on public.question_bank(user_id, topic);

alter table public.question_bank enable row level security;

drop policy if exists "Users can read own question bank" on public.question_bank;
create policy "Users can read own question bank"
on public.question_bank for select to authenticated
using (user_id in (select id from public.profiles where auth_user_id = auth.uid()));

-- Semua mutasi lewat RPC yang memverifikasi ownership.
revoke insert, update, delete on public.question_bank from authenticated, anon;
grant select on public.question_bank to authenticated;
revoke select on public.question_bank from anon;

create or replace function public.question_content_hash(
  p_content text,
  p_options jsonb,
  p_answer text
) returns text
language sql
immutable
set search_path = public
as $$
  select md5(
    lower(regexp_replace(btrim(coalesce(p_content, '')), '\s+', ' ', 'g')) || '|' ||
    coalesce(p_options::text, 'null') || '|' ||
    lower(regexp_replace(btrim(coalesce(p_answer, '')), '\s+', ' ', 'g'))
  );
$$;

create or replace function public.save_questions_to_bank(p_question_ids bigint[])
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id bigint;
  v_requested integer;
  v_owned integer;
  v_inserted integer;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();
  if v_profile_id is null then raise exception 'forbidden'; end if;

  select count(distinct id) into v_requested from unnest(p_question_ids) t(id);
  if coalesce(v_requested, 0) = 0 then raise exception 'questions_required'; end if;

  select count(distinct q.id) into v_owned
  from public.questions q
  join public.exam_sessions e on e.id = q.exam_session_id
  where q.id = any(p_question_ids) and e.user_id = v_profile_id;
  if v_owned <> v_requested then raise exception 'forbidden'; end if;

  insert into public.question_bank (
    user_id, source_question_id, subject, class_phase, topic, difficulty,
    question_type, cognitive_level, question_content, options, correct_answer,
    explanation, illustration_prompt, illustration_image, content_hash
  )
  select
    v_profile_id,
    q.id,
    e.subject,
    e.class_phase,
    case
      when jsonb_typeof(e.topics) = 'array' and jsonb_array_length(e.topics) > 0
      then nullif(
        e.topics->((greatest(q.order_number, 1) - 1) % jsonb_array_length(e.topics))->>'topik',
        ''
      )
      else null
    end,
    q.difficulty,
    q.question_type,
    q.cognitive_level,
    q.question_content,
    q.options,
    q.correct_answer,
    q.explanation,
    q.illustration_prompt,
    q.illustration_image,
    public.question_content_hash(q.question_content, q.options, q.correct_answer)
  from public.questions q
  join public.exam_sessions e on e.id = q.exam_session_id
  where q.id = any(p_question_ids) and e.user_id = v_profile_id
  on conflict (user_id, content_hash) do nothing;

  get diagnostics v_inserted = row_count;
  return jsonb_build_object(
    'requested', v_requested,
    'saved', v_inserted,
    'duplicates', v_requested - v_inserted
  );
end;
$$;

create or replace function public.delete_bank_question(p_bank_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id bigint;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();
  delete from public.question_bank where id = p_bank_id and user_id = v_profile_id;
  if not found then raise exception 'not_found'; end if;
end;
$$;

-- Membuat sesi ujian baru dari snapshot pilihan. Tidak memotong kredit karena
-- tidak ada pemanggilan AI; ini hanya memakai ulang soal yang sudah dimiliki.
create or replace function public.create_exam_from_bank(
  p_bank_ids bigint[],
  p_exam_name text default 'Paket dari Bank Soal'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id bigint;
  v_total integer;
  v_owned integer;
  v_first public.question_bank%rowtype;
  v_exam public.exam_sessions%rowtype;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();
  select count(distinct id) into v_total from unnest(p_bank_ids) t(id);
  select count(*) into v_owned from public.question_bank where user_id = v_profile_id and id = any(p_bank_ids);
  if coalesce(v_total, 0) = 0 then raise exception 'questions_required'; end if;
  if v_owned <> v_total then raise exception 'forbidden'; end if;

  select * into v_first from public.question_bank
  where user_id = v_profile_id and id = any(p_bank_ids)
  order by array_position(p_bank_ids, id) limit 1;

  insert into public.exam_sessions (
    user_id, curriculum, exam_type, class_phase, subject, semester,
    time_allocation, reference_type, difficulty, cognitive_levels,
    pg_options, include_illustration, topics, credits_consumed
  ) values (
    v_profile_id, 'Bank Soal', coalesce(nullif(btrim(p_exam_name), ''), 'Paket dari Bank Soal'),
    v_first.class_phase, v_first.subject, 'Ganjil', greatest(30, v_total * 2),
    'Bank Soal', 'Campuran', '[]'::jsonb, null, false,
    jsonb_build_array(jsonb_build_object('topik', coalesce(v_first.topic, 'Bank Soal'), 'tujuan', '')),
    0
  ) returning * into v_exam;

  insert into public.questions (
    exam_session_id, order_number, question_type, cognitive_level, difficulty,
    question_content, options, correct_answer, explanation,
    illustration_prompt, illustration_image
  )
  select
    v_exam.id, array_position(p_bank_ids, b.id), b.question_type,
    b.cognitive_level, b.difficulty, b.question_content, b.options,
    b.correct_answer, b.explanation, b.illustration_prompt, b.illustration_image
  from public.question_bank b
  where b.user_id = v_profile_id and b.id = any(p_bank_ids)
  order by array_position(p_bank_ids, b.id);

  return jsonb_build_object('exam_id', v_exam.id, 'questions_added', v_total);
end;
$$;

-- Menambahkan soal lama ke sesi ujian yang sudah ada (misalnya sesi hasil AI
-- baru). Konten yang sudah ada di target dilewati berdasarkan fingerprint.
create or replace function public.append_bank_to_exam(
  p_exam_id bigint,
  p_bank_ids bigint[]
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id bigint;
  v_total integer;
  v_owned integer;
  v_start integer;
  v_added integer;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();
  if not exists (select 1 from public.exam_sessions where id = p_exam_id and user_id = v_profile_id) then
    raise exception 'forbidden';
  end if;
  select count(distinct id) into v_total from unnest(p_bank_ids) t(id);
  select count(*) into v_owned from public.question_bank where user_id = v_profile_id and id = any(p_bank_ids);
  if coalesce(v_total, 0) = 0 then raise exception 'questions_required'; end if;
  if v_owned <> v_total then raise exception 'forbidden'; end if;

  select coalesce(max(order_number), 0) into v_start from public.questions where exam_session_id = p_exam_id;

  with candidates as (
    select b.*, row_number() over (order by array_position(p_bank_ids, b.id)) as rn
    from public.question_bank b
    where b.user_id = v_profile_id and b.id = any(p_bank_ids)
      and not exists (
        select 1 from public.questions q
        where q.exam_session_id = p_exam_id
          and public.question_content_hash(q.question_content, q.options, q.correct_answer) = b.content_hash
      )
  )
  insert into public.questions (
    exam_session_id, order_number, question_type, cognitive_level, difficulty,
    question_content, options, correct_answer, explanation,
    illustration_prompt, illustration_image
  )
  select p_exam_id, v_start + rn, question_type, cognitive_level, difficulty,
    question_content, options, correct_answer, explanation,
    illustration_prompt, illustration_image
  from candidates;

  get diagnostics v_added = row_count;
  return jsonb_build_object('exam_id', p_exam_id, 'added', v_added, 'duplicates', v_total - v_added);
end;
$$;

revoke all on function public.question_content_hash(text, jsonb, text) from public, anon;
revoke all on function public.save_questions_to_bank(bigint[]) from public, anon;
revoke all on function public.delete_bank_question(bigint) from public, anon;
revoke all on function public.create_exam_from_bank(bigint[], text) from public, anon;
revoke all on function public.append_bank_to_exam(bigint, bigint[]) from public, anon;

grant execute on function public.save_questions_to_bank(bigint[]) to authenticated;
grant execute on function public.delete_bank_question(bigint) to authenticated;
grant execute on function public.create_exam_from_bank(bigint[], text) to authenticated;
grant execute on function public.append_bank_to_exam(bigint, bigint[]) to authenticated;
